# spring web 内嵌服务器(默认tomcat)的启动端口
database: mysql
server:
  port: ${PORT:8080}
spring:
  application:
    name: template
  # 定义数据源，连接数据库的信息
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_d577e45ead18344
    #url: ${MYSQL_URL:jdbc:mysql://default.cs-asia-east1-jnrc.cloudshell.dev:3306/template}
    # mysql 版本为8以下请使用 `com.mysql.jdbc.Driver`
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver
    username: ba4f8fd380da5e
    password: e8cc7907
    #initialization-mode: always
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
mybatis:
  mapper-locations: classpath:mapper/*.xml